AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DuplicateMethods:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  AllowedMethods:
    - size_from_win_api

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "**/*.gemspec"

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - size

Metrics/MethodLength:
  AllowedMethods:
    - size_from_win_api

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  AllowedMethods:
    - size

Naming/FileName:
  Exclude:
    - "lib/tty-screen.rb"

Style/BlockDelimiters:
  AllowedMethods:
    - expect
    - let

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/CommentedKeyword:
  Enabled: false

Style/FetchEnvVar:
  AllowedVars:
    - COVERAGE

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/ParallelAssignment:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
